name: Android CI - Unit Tests

on:
  # (Trigger): Workflow akan berjalan pada event berikut
  push:
    branches: [ "main" ] # Setiap kali ada push ke branch main

jobs:
  unit_test:
    # Mengatur lingkungan virtual untuk menjalankan workflow
    runs-on: ubuntu-latest

    # Langkah-langkah yang akan dijalankan
    steps:

      # 1. Checkout Code: Mendapatkan salinan kode dari repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Setup JDK: Menginstal Java Development Kit (JDK) yang diperlukan oleh Gradle
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Setup Gradle: Menyiapkan cache Gradle untuk mempercepat build
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      # 4. Izin Eksekusi
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 5. Run Unit Tests: Menjalankan semua Local Unit Tests (berjalan di JVM)
      #    Menggunakan gradlew (Gradle Wrapper) untuk memastikan versi yang benar.
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest